# Series

In [15]:
# Importações
import pandas as pd
import numpy as np
import statistics as sts

In [16]:
# Importar apenas Series
from pandas import Series

In [17]:
# Versão
pd.__version__

'1.1.3'

In [18]:
# Criando uma série sem especificar os índices
serie = Series([1,6,3,8,9,4])

In [19]:
serie

0    1
1    6
2    3
3    8
4    9
5    4
dtype: int64

In [20]:
# Listando os valores
serie.values

array([1, 6, 3, 8, 9, 4])

In [21]:
# Listando os indexs
serie.index

RangeIndex(start=0, stop=6, step=1)

In [22]:
# Serie com valores variados
ser = Series([3,4,5, 'Ois', np.nan, 3,-4]); ser

0      3
1      4
2      5
3    Ois
4    NaN
5      3
6     -4
dtype: object

In [23]:
# Criando uma série e especificando os índices
serie2 = Series([3,7,5,4,7], index=['a', 'b', 'c', 'd', 'e'])

In [24]:
serie2

a    3
b    7
c    5
d    4
e    7
dtype: int64

In [25]:
serie2.values

array([3, 7, 5, 4, 7])

In [26]:
serie2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [27]:
# Lista valor especifico de um index
serie2['a']

3

In [28]:
# Pode usar o indice numerico
serie2[1]

7

In [29]:
# Lista de dados e de indices
dados = ["DF", "Santa Maria", "Gama"]
indices = [1,2,3]

In [30]:
serie3 = Series(data=dados, index=indices)

In [31]:
# Listando apenas os valores maiores que 3
serie2[serie2 > 3]

b    7
c    5
d    4
e    7
dtype: int64

In [32]:
# Retorna True se existe o index passado na serie
'c' in serie2

True

In [33]:
# Criando uma série de dados passando um dicionário como parâmetro
dict = {'Cientista':20000, 'Professor': 2000, 'Editor de videos':3000, 'Engenheiro':15000}

In [34]:
# Criando uma série a partir de um dicionário
serie3 = Series(dict)

In [35]:
serie3

Cientista           20000
Professor            2000
Editor de videos     3000
Engenheiro          15000
dtype: int64

In [36]:
type(serie3)

pandas.core.series.Series

In [37]:
# Chama valor a partir do indice
serie3['Cientista']

20000

In [38]:
# Chama valor a partir do indice
serie3[3]

15000

In [39]:
# Criando uma lista para atribuir aos indices
lista = ['Cientista', 'Professor', 'Editor de videos', 'Engenheiro', 'Arquiteto']

In [40]:
# Criando uma serie e usando uma lista como índice
serie4 = Series(dict, index= lista)

In [41]:
# Não mudou muito, apenas adicionou o Arquiteto
serie4

Cientista           20000.0
Professor            2000.0
Editor de videos     3000.0
Engenheiro          15000.0
Arquiteto               NaN
dtype: float64

In [42]:
# Retorna True com os dados nulos se houver
pd.isnull(serie4)

Cientista           False
Professor           False
Editor de videos    False
Engenheiro          False
Arquiteto            True
dtype: bool

In [43]:
# Retorna True com os dados não nulos
pd.notnull(serie4)

Cientista            True
Professor            True
Editor de videos     True
Engenheiro           True
Arquiteto           False
dtype: bool

In [44]:
# Concatenando Series
serie3 + serie4

Arquiteto               NaN
Cientista           40000.0
Editor de videos     6000.0
Engenheiro          30000.0
Professor            4000.0
dtype: float64

In [45]:
# Nomeando a Serie
serie4.name = 'Mercado de trabalho'

In [46]:
# Nomeando o index
serie4.index.name =  'Profissões'

In [47]:
serie4

Profissões
Cientista           20000.0
Professor            2000.0
Editor de videos     3000.0
Engenheiro          15000.0
Arquiteto               NaN
Name: Mercado de trabalho, dtype: float64

In [48]:
# Conta o total de valores individuais
serie.value_counts()

6    1
4    1
3    1
9    1
1    1
8    1
dtype: int64

# Operações 

In [49]:
idades = Series([67, 78, 45, 33, 39, 22, 18, 20, 19, 20, 30])

In [50]:
# Valores únicos
idades.unique()

array([67, 78, 45, 33, 39, 22, 18, 20, 19, 30])

In [51]:
# Soma
idades.sum()

391

In [52]:
# Média
idades.mean()

35.54545454545455

In [53]:
# Tipo de dados
idades.dtypes

dtype('int64')

In [54]:
# Descrição
idades.describe()

count    11.000000
mean     35.545455
std      20.441936
min      18.000000
25%      20.000000
50%      30.000000
75%      42.000000
max      78.000000
dtype: float64

In [55]:
idades.head()

0    67
1    78
2    45
3    33
4    39
dtype: int64

In [56]:
idades[0:3]

0    67
1    78
2    45
dtype: int64

In [57]:
# Contagem de elementos
idades.count(); len(idades)

11

In [58]:
# Máximo
idades.max()

78

In [59]:
# Mínimo
idades.min()

18

In [60]:
# Mediana
sts.median(idades)

30

In [61]:
# Moda
sts.mode(idades)

20

# Fim